### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by ajhalls** [animachine/animachine#7]
I get the following error when running it on CentOS, does it require Ubuntu?:
```

➜  animachine git:(master) ✗ npm install        
animachine@0.1.0 /var/www/html/css.ink/animachine
├── UNMET PEER DEPENDENCY react@15.4.2 invalid
└─┬ webpack@1.14.0
  └─┬ node-libs-browser@0.7.0 
    ├─┬ buffer@4.9.1 
    │ └── base64-js@1.2.0 
    ├── constants-browserify@1.0.0 
    ├─┬ crypto-browserify@3.3.0 
    │ └── browserify-aes@0.4.0 
    ├── https-browserify@0.0.1 
    ├── os-browserify@0.2.1 
    ├── stream-browserify@2.0.1 
    ├─┬ stream-http@2.6.2 
    │ ├── builtin-status-codes@3.0.0 
    │ └── to-arraybuffer@1.0.1 
    ├── timers-browserify@2.0.2 
    └─┬ url@0.11.0 
      └── punycode@1.3.2 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
npm WARN @azazdeaz/component-playground@0.1.2 requires a peer of react@0.13.x but none was installed.
npm WARN react-dom@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN mobservable-react@2.1.5 requires a peer of react@^0.14.0 but none was installed.
npm WARN mobservable-react@2.1.5 requires a peer of react-dom@^0.14.0 but none was installed.
npm WARN react-dnd@1.1.8 requires a peer of react@>=0.13.0 <0.15.0 || ^0.14.0-rc1 but none was installed.
npm WARN react-dom@0.14.8 requires a peer of react@^0.14.8 but none was installed.
npm WARN react-dom@0.14.8 requires a peer of react@^0.14.8 but none was installed.


animachine git:(master) ✗ gulp            
[17:03:39] Using gulpfile /var/www/html/css.ink/animachine/gulpfile.js
[17:03:39] Starting 'webpack-dev-server'...
[17:03:39] [webpack-dev-server] http://localhost:5435/webpack-dev-server/index.html
Error: illegal operation on a directory
    at MemoryFileSystem.writeFileSync (/var/www/html/animachine/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:211:9)
    at MemoryFileSystem.writeFile (/var/www/html/animachine/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:324:8)
    at Compiler.writeOut (/var/www/html/animachine/node_modules/webpack/lib/Compiler.js:261:27)
    at Compiler.<anonymous> (/var/www/html/animachine/node_modules/webpack/lib/Compiler.js:246:20)
    at /var/www/html/animachine/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/var/www/html/animachine/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/var/www/htm/animachine/node_modules/async/lib/async.js:209:22)
    at Compiler.emitFiles (/var/www/html/animachine/node_modules/webpack/lib/Compiler.js:235:20)
    at Immediate.<anonymous> (/var/www/html/animachine/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:637:20)
```

**Comment by azazdeaz** [comment]
Hi @ajhalls, maybe this can help: http://stackoverflow.com/a/37645484/6749232

**Comment by ajhalls** [comment]
Thanks for the reply, but I get the same errors minus the OS error. I am fairly new to Node, but this doesn't seem to be as much a problem with your app as my choice of OS / env. I could maybe troubleshoot the React issues more.

**Comment by atefth** [comment]
I seem to be getting this error when I run `gulp webpack-dev-server`:

`[03:12:01] Using gulpfile ~/code/javascript/gsap/animachine/gulpfile.js`
`[03:12:01] Starting 'webpack-dev-server'...`
`[03:12:01] 'webpack-dev-server' errored after 85 ms`
`[03:12:01] TypeError: webpack.validateSchema is not a function`
`    at new Server (/Users/atefth/code/javascript/gsap/animachine/node_modules/webpack-dev-server/lib/Server.js:25:35)`
`    at Gulp.<anonymous> (/Users/atefth/code/javascript/gsap/animachine/gulpfile.js:21:2)`
`    at module.exports (/Users/atefth/code/javascript/gsap/animachine/node_modules/orchestrator/lib/runTask.js:34:7)`
`    at Gulp.Orchestrator._runTask (/Users/atefth/code/javascript/gsap/animachine/node_modules/orchestrator/index.js:273:3)`
`    at Gulp.Orchestrator._runStep (/Users/atefth/code/javascript/gsap/animachine/node_modules/orchestrator/index.js:214:10)`
`    at Gulp.Orchestrator.start (/Users/atefth/code/javascript/gsap/animachine/node_modules/orchestrator/index.js:134:8)`
`    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20`
`    at _combinedTickCallback (internal/process/next_tick.js:67:7)`
`    at process._tickCallback (internal/process/next_tick.js:98:9)`
`    at Function.Module.runMain (module.js:577:11)`

Any solutions?
